### ISSUE TITLE
2 textures and 1 crafting recipe

### ISSUE THREAD

**Issue by Mandelbrot2671** [Draylar/vanilla-excavators#1]
**nether_excavator** image texture doesn't exist.
**vibranium_excavator** model calls **vibranium_hammer** texture
**glowstone_excavator** is not able to craft 

I love the mod and I'll continue testing future versions to make it as good as vanilla hammers mod is <3 .

**Comment by Draylar** [comment]
Thanks for the report & your time; much appreciated. I just pushed a 1.0.2 release that (should?) fix these issues. :heart:
