### ISSUE TITLE
Fabric API 0.4.2 compatability issue

### ISSUE THREAD

**Issue by tehbasshunter** [Draylar/vanilla-excavators#3]
Same issue with Vanilla Hammers applies with this as well.

https://github.com/Draylar/vanilla-hammers/issues/37
https://paste.ee/p/UpI58#s=0&l=194

**Comment by tehbasshunter** [comment]
Any chance to port the fix over to this mod as well?

**Comment by Draylar** [comment]
Thanks for your patience; I just pushed 1.1.0 on [GitHub](https://github.com/Draylar/vanilla-excavators/releases/tag/1.1.0-1.14.4) and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators/files/2942069), which should fix this issue.
