### ISSUE TITLE
Crash - Fabric 0.8.9 Build 203 - Vanilla excavators 1.1.0

### ISSUE THREAD

**Issue by shikyo13** [Draylar/vanilla-excavators#4]
Can craft excavators but when trying to switch to them in the hotbar, game crashes. 

Crash Report - https://pastebin.com/ENEfKtQB

Only way to get back into the server once this has happened is to delete the playerdata file thus clearing inventory.

**Comment by Draylar** [comment]
1.1.0 is for 1.15. 1.2.0 was recently released with 1.16 support. Thanks for the report!
