### ISSUE TITLE
[Bug Report] (1.16.1) Wood Excavator doesn't destroy in a 3x3 grid

### ISSUE THREAD

**Issue by Abbanon** [Draylar/vanilla-excavators#8]
*(I originally made a comment [on the CurseForge mod page](https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators?comment=45) but then later realized here would be a better place to report this.)*

The Wooden Excavator is only destroying the  middle/targeted block on shovel-compatible ground, despite playing the breaking animation over the entire 3x3 grid area.
All other Excavators (and even Hammers) work as intended, it's just the Wooden Excavator giving trouble.

I'm using the latest mod version (vanillaexcavators-2.0.0-1.16.1)

**Comment by Draylar** [comment]
Should:tm: be fixed in 2.1.0 for 1.16.2. Let me know if the issue persists.

**Comment by Abbanon** [comment]
Would it be possible to see this change in 1.16.1 as well?

**Comment by Abbanon** [comment]
Okay so now a new problem has developed when using the new 2.1.0 update (in 1.16.1).
*(Haven't tested 1.16.2, but the mod itself seems to load just fine in 1.16.1)*

In ***creative mode***, Wooden Excavators still only break a single block instead of a 3x3 area, and now it doesn't play the breaking animations on the surrounding blocks like it did in the previous version.
But in ***survival mode***, using any Excavator crashes the game.

*Survival mode crash report:*
[crash-2020-09-11_09.43.33-server.txt](https://github.com/Draylar/vanilla-excavators/files/5209377/crash-2020-09-11_09.43.33-server.txt)


*Here's a screenshot of the 6 default Excavator types in Creative mode:*
*Wooden, Stone, Iron, Gold, Diamond, and Netherite.*
![2020-09-11_09 30 54](https://user-images.githubusercontent.com/37251822/92932369-d2b6b780-f412-11ea-8c78-6fc062a88bd2.png)

**Comment by Draylar** [comment]
Seems like an issue with how my library checked for practical effectiveness (like, if the speed of the tool/block is > n, you can break it)... Wooden Excavators were too slow to fit that check, haha. I fixed it making them slightly faster in 2.1.1. Thanks again for the report!
